---
deployment:
  tasks:
    - export DEPLOYPATH=/home/smartiot/bell.smartiotindo.com/smartbell-laravel
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && /usr/local/bin/composer install --optimize-autoloader --no-dev
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
    - cd $DEPLOYPATH && php artisan migrate --force
